import React from 'react';
import { useRouter } from 'next/router'
import Head from 'next/head'
import BoardPage from '../src/container/BoardPage';
import { ThemeProvider } from 'styled-components'
import Themes from '../styles/themes'
import { handler } from "./api/cards";

function Board({ cards }) {
  const router = useRouter()
  const { side } = router.query
  
  const theme = {
    play: Themes[side || 'jedi'],
    comp: Themes[side === 'jedi' ? 'sith' : 'jedi']
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <BoardPage side={side} cards={cards} />
      </ThemeProvider>
    </div>
  );
}

export default Board;

export const getStaticProps = async () => {
  const database = await handler();

  return {
    props: {
      cards: database,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every second
    // revalidate: 1, // In seconds
  };
};