import React from 'react';
import { useRouter } from 'next/router'
import Head from 'next/head'
import BoardPage from '../src/container/BoardPage';
import { ThemeProvider } from 'styled-components'
import Themes from '../styles/themes'

function Board() {
  const router = useRouter()
  const { side } = router.query

  const theme = {
    play: Themes[side],
    comp: Themes[side === 'jedi' ? 'sith' : 'jedi']
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <BoardPage side={side} />
      </ThemeProvider>
    </div>
  );
}

export default Board;